const CLIENT_ROLE="cliente",TEMP_BOOKING_KEY="agendamento_temp";
const VISUAL_CATEGORIES={unhas:"Unhas",olhos:"Olhos",corpo:"Corpo"};
const servicesLoading=document.querySelector("#services-loading"),servicesContent=document.querySelector("#services-content"),bookingMessage=document.querySelector("#booking-message");
let servicesCatalog=[],professionalLinks=[],selectedVisualCategory="unhas",selectedItems=[];
function showMessage(text=""){bookingMessage.textContent=text;bookingMessage.className=text?"message error":"message"}
function money(value){return Number(value).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function norm(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function visualCategory(service){const text=`${norm(service.category)} ${norm(service.name)}`;if(/cilio|sobrancelha|lash|brow|olho|volume|fox eyes/.test(text))return"olhos";if(/quiroprax|massag|massoter|limpeza de pele|ventosa|acupunt|corpo|bem-estar|estetica/.test(text))return"corpo";return"unhas"}
function serviceProfessionals(serviceId){const unique=new Map();professionalLinks.filter(link=>String(link.servico_id)===String(serviceId)).forEach(link=>{const professional=Array.isArray(link.profissionais)?link.profissionais[0]:link.profissionais;if(professional?.id)unique.set(professional.id,professional)});return[...unique.values()]}
function assignedProfessional(service){const category=visualCategory(service),available=serviceProfessionals(service.id),categoryProfessionals=new Map();servicesCatalog.filter(item=>visualCategory(item)===category).forEach(item=>serviceProfessionals(item.id).forEach(professional=>categoryProfessionals.set(professional.id,professional)));if(categoryProfessionals.size===1){const automatic=[...categoryProfessionals.values()][0];if(available.some(professional=>professional.id===automatic.id))return automatic}const preference=category==="unhas"?/celyne/:category==="olhos"?/viviane/:null;return preference?available.find(professional=>preference.test(norm(professional.name))):null}
async function requireClient(){const{data,error}=await supabaseClient.auth.getSession();if(error)throw error;if(!data.session){location.replace("login.html");return false}const profile=await supabaseClient.from("profiles").select("role").eq("id",data.session.user.id).maybeSingle();if(profile.error)throw profile.error;if(profile.data?.role!==CLIENT_ROLE)throw new Error("Este perfil não possui acesso ao agendamento da cliente.");return true}
function save(){localStorage.setItem(TEMP_BOOKING_KEY,JSON.stringify({itens:selectedItems.map((item,index)=>({...item,ordem:index+1}))}))}
function renderSelection(){const summary=document.querySelector("#selection-summary");summary.hidden=!selectedItems.length;document.querySelector("#selection-count").textContent=`${selectedItems.length} ${selectedItems.length===1?"procedimento":"procedimentos"}`;const duration=selectedItems.reduce((sum,item)=>sum+Number(item.duracao_minutos||0),0),price=selectedItems.reduce((sum,item)=>sum+Number(item.valor||0),0);document.querySelector("#selection-totals").textContent=`${duration} min · ${money(price)}`;const list=document.querySelector("#selection-list");list.replaceChildren();selectedItems.forEach((item,index)=>{const row=document.createElement("div");const info=document.createElement("div");info.className="selection-item-info";const name=document.createElement("strong");name.textContent=`${index+1}. ${item.servico_nome}`;info.appendChild(name);if(item.profissional_nome){const professional=document.createElement("span");professional.textContent=item.profissional_nome;info.appendChild(professional)}const actions=document.createElement("div");actions.className="selection-item-actions";[["↑",-1,"Mover para cima"],["↓",1,"Mover para baixo"]].forEach(([text,offset,label])=>{const button=document.createElement("button");button.type="button";button.className="selection-action";button.textContent=text;button.title=label;button.disabled=index+offset<0||index+offset>=selectedItems.length;button.addEventListener("click",()=>{const target=index+offset;[selectedItems[index],selectedItems[target]]=[selectedItems[target],selectedItems[index]];renderSelection()});actions.appendChild(button)});const remove=document.createElement("button");remove.type="button";remove.className="selection-action remove";remove.textContent="×";remove.title="Remover";remove.addEventListener("click",()=>{selectedItems.splice(index,1);renderSelection()});actions.appendChild(remove);row.append(info,actions);list.appendChild(row)});document.querySelectorAll("[data-service-id]").forEach(button=>{const count=selectedItems.filter(item=>String(item.servico_id)===button.dataset.serviceId).length;button.textContent=count?`Adicionar novamente (${count})`:"Adicionar"});save()}
function addService(service){if(selectedItems.length>=10)return showMessage("O limite é de 10 procedimentos por agendamento.");const professional=assignedProfessional(service);selectedItems.push({servico_id:service.id,servico_nome:service.name,categoria:service.category,duracao_minutos:Number(service.duration_minutes),valor:Number(service.price),requires_deposit:service.requires_deposit_default===true,deposit_percent:Number(service.deposit_percent_default||0),profissional_id:professional?.id||"",profissional_nome:professional?.name||""});showMessage();renderSelection()}
function card(service){const article=document.createElement("article");article.className="service-card";const category=document.createElement("span");category.className="service-category";category.textContent=service.category||"Serviço";const title=document.createElement("h3");title.textContent=service.name;const description=document.createElement("p");description.className="service-description";description.textContent=service.description||"Consulte os detalhes com nossa equipe.";const details=document.createElement("div");details.className="service-details";details.innerHTML=`<span>${Number(service.duration_minutes)} min</span><strong>${money(service.price)}</strong>`;const button=document.createElement("button");button.type="button";button.dataset.serviceId=service.id;button.addEventListener("click",()=>addService(service));article.append(category,title,description,details,button);return article}
function renderServices(){servicesContent.replaceChildren();const group=document.createElement("section");group.className="service-group";const heading=document.createElement("h2");heading.textContent=VISUAL_CATEGORIES[selectedVisualCategory];const grid=document.createElement("div");grid.className="service-grid";servicesCatalog.filter(item=>visualCategory(item)===selectedVisualCategory).forEach(item=>grid.appendChild(card(item)));group.append(heading,grid);servicesContent.appendChild(group);servicesLoading.hidden=true;servicesContent.hidden=false;renderSelection()}
async function init(){try{if(!await requireClient())return;const saved=JSON.parse(localStorage.getItem(TEMP_BOOKING_KEY)||"null");selectedItems=Array.isArray(saved?.itens)?saved.itens:[];const[servicesResult,linksResult]=await Promise.all([supabaseClient.from("servicos").select("id,name,category,description,duration_minutes,price,requires_deposit_default,deposit_percent_default").eq("active",true).order("name"),supabaseClient.from("profissional_servicos").select("servico_id,profissionais!inner(id,name,active)").eq("active",true).eq("profissionais.active",true)]);if(servicesResult.error)throw servicesResult.error;if(linksResult.error)throw linksResult.error;servicesCatalog=servicesResult.data||[];professionalLinks=linksResult.data||[];selectedItems=selectedItems.map(item=>{const service=servicesCatalog.find(entry=>String(entry.id)===String(item.servico_id)),professional=service?assignedProfessional(service):null;return professional?{...item,profissional_id:professional.id,profissional_nome:professional.name}:item});renderServices()}catch(error){servicesLoading.hidden=true;showMessage(error.message||"Não foi possível carregar os serviços.")}}
document.querySelectorAll("[data-service-category]").forEach(button=>button.addEventListener("click",()=>{selectedVisualCategory=button.dataset.serviceCategory;document.querySelectorAll("[data-service-category]").forEach(item=>{const active=item===button;item.classList.toggle("is-active",active);item.setAttribute("aria-pressed",String(active))});renderServices()}));
document.querySelector("#continue-button").addEventListener("click",()=>{if(selectedItems.length)location.assign("agendar-profissional.html")});init();
