const CLIENT_ROLE="cliente",TEMP_BOOKING_KEY="agendamento_temp",SLOT_INTERVAL_MINUTES=5;
const dateInput=document.querySelector("#booking-date"),timesContainer=document.querySelector("#available-times"),timesLoading=document.querySelector("#times-loading"),message=document.querySelector("#booking-message");let booking;
function showMessage(text=""){message.textContent=text;message.className=text?"message error":"message"}
function readBooking(){try{const value=JSON.parse(localStorage.getItem(TEMP_BOOKING_KEY));return Array.isArray(value?.itens)&&value.itens.length&&value.itens.every(item=>item.profissional_id)?value:null}catch{return null}}
async function requireClient(){const session=await supabaseClient.auth.getSession();if(session.error)throw session.error;if(!session.data.session){location.replace("login.html");return false}const profile=await supabaseClient.from("profiles").select("role").eq("id",session.data.session.user.id).maybeSingle();if(profile.error)throw profile.error;if(profile.data?.role!==CLIENT_ROLE)throw new Error("Acesso permitido somente para clientes.");return true}
function timeMinutes(value){const raw=typeof value==="string"?value:(value?.horario??value?.hora??value?.hora_inicio??value?.start_time??value?.horaInicio??value?.startAt??"");const match=String(raw).match(/(?:T|^)(\d{2}):(\d{2})/);return match?Number(match[1])*60+Number(match[2]):null}
function timeText(minutes){return`${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`}
async function availability(date){let elapsed=0,possible=null;for(const item of booking.itens){const{data,error}=await supabaseClient.rpc("get_horarios_disponiveis",{p_profissional_id:item.profissional_id,p_servico_id:item.servico_id,p_data:date,p_intervalo_minutos:SLOT_INTERVAL_MINUTES});if(error)throw error;const starts=new Set((data||[]).map(timeMinutes).filter(Number.isFinite).map(value=>value-elapsed));possible=possible===null?starts:new Set([...possible].filter(value=>starts.has(value)));elapsed+=Number(item.duracao_minutos)}return[...(possible||[])].filter(value=>value>=0&&value%30===0).sort((a,b)=>a-b)}
function choose(date,start){const duration=booking.itens.reduce((sum,item)=>sum+Number(item.duracao_minutos),0);booking.data=date;booking.hora_inicio=timeText(start);booking.hora_fim=timeText(start+duration);localStorage.setItem(TEMP_BOOKING_KEY,JSON.stringify(booking));location.assign("agendar-confirmacao.html")}
function renderTimes(date,values){timesContainer.replaceChildren();if(!values.length){const empty=document.createElement("p");empty.className="empty-state";empty.textContent="Não há uma sequência disponível nesta data.";timesContainer.appendChild(empty);return}values.forEach(value=>{const button=document.createElement("button");button.type="button";button.className="time-button";button.textContent=timeText(value);button.addEventListener("click",()=>choose(date,value));timesContainer.appendChild(button)})}
async function onDate(){if(!dateInput.value)return;showMessage();timesLoading.hidden=false;timesContainer.replaceChildren();try{renderTimes(dateInput.value,await availability(dateInput.value))}catch(error){showMessage(error.message||"Não foi possível consultar os horários.");renderTimes(dateInput.value,[])}finally{timesLoading.hidden=true}}
function renderSummary(){const summary=document.querySelector("#booking-summary");summary.replaceChildren();booking.itens.forEach((item,index)=>{const row=document.createElement("div");const label=document.createElement("span");label.textContent=`${index+1}. ${item.servico_nome}`;const value=document.createElement("strong");value.textContent=`${item.profissional_nome} · ${item.duracao_minutos} min`;row.append(label,value);summary.appendChild(row)})}
async function init(){booking=readBooking();if(!booking)return location.replace("agendar-profissional.html");renderSummary();dateInput.min=new Date().toLocaleDateString("sv-SE");try{if(await requireClient())dateInput.addEventListener("change",onDate)}catch(error){dateInput.disabled=true;showMessage(error.message||"Não foi possível validar o acesso.")}}init();
